### ISSUE TITLE
About FDR calculation in Extended Data Fig. 4 c and d 

### ISSUE THREAD

**Issue by yuanjianwen-gif** [idekerlab/MuSIC#4]
Hi, great work MuSIC did!  But I can not understand what kind of test you took and how to calculate FDR in Extended Data Fig. 4 c and d.  

Appreciate that if you have time to explain!

The only explanation I could find in the method was:
For each hierarchy, we recorded the number of Human Cell Map protein-protein interactions (x) or DepMap co-essential protein pairs (y) that were covered by systems that significantly enriched (FDR ≤ 0.1) for those interactions (Extended Data Fig. 4c, d).

**Comment by yueqin-sysbio** [comment]
Hi! For Extended Data Fig. 4c and d, we used hypergeometric test to evaluate the enrichment of protein pairs (i.e. Human Cell Map protein-protein interactions) in each subcellular system from the hierarchy. The p-values from hypergeometric test were further corrected for multiple hypothesis testing using Benjamini-Hochberg procedure to obtain the FDR.

**Comment by yuanjianwen-gif** [comment]
Hi, thanks for your reply!
 And I am still confused about what the parameters (N, K, n, k)   are supposed to be. 
If there are 5 proteins in one specific system, 5x4/2 = 10 possible interactions among them, and 4 interactions overlap with 178 interactions from the Human Cell Map, I wonder if : 
N = 661 x 660/2, the number of all possible interactions among the 661 proteins;  
K = 178 protein-protein interactions from the Human Cell Map with high confidence; 
n = 10;
k = 4

**Comment by yueqin-sysbio** [comment]
The four values you are using are correct except I calculated enrichment among genes with observation, meaning among genes that overlapped between Human Cell Map and MuSIC. However, the exact association between N, K, n, k variables and values depend on the specific definition of the variables, which I cannot confirm as the definition might vary among different method descriptions.

**Comment by yueqin-sysbio** [comment]
To help users with hierarchy evaluation, I have uploaded code and example data for enrichment analysis. Please see [hierarchy_evaluation.py](https://github.com/idekerlab/MuSIC/blob/master/hierarchy_evaluation.py) and [HumanCellMap_edge_matrix.csv](https://github.com/idekerlab/MuSIC/blob/master/Examples/HumanCellMap_edge_matrix.csv)

**Comment by yuanjianwen-gif** [comment]
Thanks very much！
